
export const capitals = [
    'Mariehamn',
    'Tirana',
    'Andorra la Vella',
    'Vienna',
    'Minsk',
    'Brussels',
    'Sarajevo',
    'Sofia',
    'Zagreb',
    'Prague',
    'Copenhagen',
    'Tallinn',
    'Tórshavn',
    'Helsinki',
    'Paris',
    'Berlin',
    'Gibraltar',
    'Athens',
    'Saint Peter Port',
    'Budapest',
    'Reykjavík',
    'Dublin',
    'Douglas',
    'Rome',
    'Saint Helier',
    'Pristina',
    'Riga',
    'Vaduz',
    'Vilnius',
    'Luxembourg',
    'Valletta',
    'Chisinau',
    'Podgorica',
    'Amsterdam',
    'Skopje',
    'Oslo',
    'Warsaw',
    'Lisbon',
    'Monaco',
    'Bucharest',
    'Moscow',
    'San Marino',
    'Belgrade',
    'Bratislava',
    'Ljubljana',
    'Madrid',
    'Longyearbyen',
    'Stockholm',
    'Bern',
    'Kiev',
    'London',
    'Città del Vaticano',
    'The Valley',
    'Saint John’s',
    'Buenos Aires',
    'Oranjestad',
    'Nassau',
    'Bridgetown',
    'Belmopan',
    'Hamilton',
    'Sucre',
    'Brasília',
    'Road Town',
    'Ottawa',
    'George Town',
    'Santiago',
    'Bogotá',
    'San José',
    'Havana',
    'Willemstad',
    'Roseau',
    'Santo Domingo',
    'Quito',
    'San Salvador',
    'Stanley',
    'Cayenne',
    'Nuuk',
    "Saint George's",
    'Basse-Terre',
    'Guatemala City',
    'Georgetown',
    'Port-au-Prince',
    'Tegucigalpa',
    'Fort-de-France',
    'Mexico City',
    'Brades',
    'Managua',
    'Panama City',
    'Asunción',
    'Lima',
    'San Juan',
    'Gustavia',
    'Basseterre',
    'Castries',
    'Marigot',
    'Saint-Pierre',
    'Kingstown',
    'Philipsburg',
    'King Edward Point',
    'Paramaribo',
    'Port-of-Spain',
    'Cockburn Town',
    'Washington, D.C.',
    'Montevideo',
    'Caracas',
    'Charlotte Amalie',
    'Kabul',
    'Yerevan',
    'Baku',
    'Manama',
    'Dhaka',
    'Thimphu',
    'Bandar Seri Begawan',
    'Nay Pyi Taw',
    'Phnom Penh',
    'Beijing',
    'Nicosia',
    'Dili',
    'Tbilisi',
    'Hong Kong',
    'New Delhi',
    'Jakarta',
    'Tehran',
    'Baghdad',
    'Jerusalem',
    'Tokyo',
    'Amman',
    'Nursultan',
    'Kuwait City',
    'Bishkek',
    'Vientiane',
    'Beirut',
    'Concelho de Macau',
    'Kuala Lumpur',
    'Malé',
    'Ulaanbaatar',
    'Kathmandu',
    'Pyongyang',
    'Muscat',
    'Islamabad',
    'Ramallah',
    'Manila',
    'Doha',
    'Riyadh',
    'Singapore',
    'Seoul',
    'Colombo',
    'Damascus',
    'Taipei',
    'Dushanbe',
    'Bangkok',
    'Ankara',
    'Ashgabat',
    'Abu Dhabi',
    'Tashkent',
    'Hanoi',
    'Sanaa',
    'Canberra',
    'Flying Fish Cove',
    'West Island',
    'Wellington',
    'Kingston'
];
